In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Def voc size

voc_size =1000

In [6]:
# One hot representation

one_hot_rep = [one_hot(words , voc_size) for words in sent]

one_hot_rep

[[584, 524, 818, 833],
 [584, 524, 818, 736],
 [584, 324, 818, 669],
 [664, 94, 472, 142, 578],
 [664, 94, 472, 142, 146],
 [655, 584, 613, 818, 621],
 [786, 233, 103, 142]]

In [7]:
## word embedding reprenstation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 584 524 818 833]
 [  0   0   0   0 584 524 818 736]
 [  0   0   0   0 584 324 818 669]
 [  0   0   0 664  94 472 142 578]
 [  0   0   0 664  94 472 142 146]
 [  0   0   0 655 584 613 818 621]
 [  0   0   0   0 786 233 103 142]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 62ms/step


array([[-0.04939009, -0.01086538, -0.04416729, -0.01467624,  0.01290606,
         0.0246048 , -0.01550733, -0.04742545,  0.01140003, -0.0411031 ],
       [-0.04939009, -0.01086538, -0.04416729, -0.01467624,  0.01290606,
         0.0246048 , -0.01550733, -0.04742545,  0.01140003, -0.0411031 ],
       [-0.04939009, -0.01086538, -0.04416729, -0.01467624,  0.01290606,
         0.0246048 , -0.01550733, -0.04742545,  0.01140003, -0.0411031 ],
       [-0.04939009, -0.01086538, -0.04416729, -0.01467624,  0.01290606,
         0.0246048 , -0.01550733, -0.04742545,  0.01140003, -0.0411031 ],
       [ 0.00790328,  0.00894957,  0.01814086,  0.01186538, -0.02958292,
         0.01398051,  0.04699644, -0.03718107,  0.04644466,  0.01013038],
       [-0.03269781, -0.00965453,  0.0450612 , -0.02899098, -0.01134963,
        -0.00834918,  0.01850191, -0.030643  ,  0.00876822, -0.0252463 ],
       [-0.03562496,  0.02246196,  0.03845099,  0.02217293, -0.04231824,
        -0.03166231, -0.00577108, -0.03086859

In [15]:
embedded_docs[0]

array([  0,   0,   0,   0, 584, 524, 818, 833])